### ISSUE TITLE
Todo Tracking

### ISSUE THREAD

**Issue by andreasgrafen** [andreasgrafen/andreasgrafen#1]
**Accessibility**
- [ ] Cursor without Canvas/JS
- [ ] Uptime without JS
- [ ] Nav on Imprint subpage
<br>

**Enhancements**
- [ ] Scroll Snapping ?
- [ ] Error Page

**Comment by andreasgrafen** [comment]
obsolete due to rewrite
